fullnameOverride: ingress-nginx-internal
controller:
  service:
    annotations:
      lbipam.cilium.io/ips: 192.168.1.52
    externalTrafficPolicy: Cluster
  ingressClassResource:
    name: internal
    default: true
    controllerValue: k8s.io/internal
  admissionWebhooks:
    objectSelector:
      matchExpressions:
        - key: ingress-class
          operator: In
          values:
            - internal
  config:
    allow-snippet-annotations: true
    annotations-risk-level: Critical
    # taken from https://github.com/ai-robots-txt/ai.robots.txt
    block-user-agents: AdsBot-Google,Amazonbot,anthropic-ai,Applebot-Extended,Bytespider,CCBot,ChatGPT-User,ClaudeBot,Claude-Web,cohere-ai,Diffbot,FacebookBot,FriendlyCrawler,Google-Extended,GoogleOther,GPTBot,img2dataset,omgili,omgilibot,peer39_crawler,peer39_crawler/1.0,PerplexityBot,YouBot,
    client-body-buffer-size: 100M
    client-body-timeout: 120
    client-header-timeout: 120
    enable-brotli: "true"
    enable-ocsp: "true"
    enable-real-ip: "true"
    force-ssl-redirect: "true"
    hide-headers: Server,X-Powered-By
    hsts-max-age: 31449600
    keep-alive-requests: 10000
    keep-alive: 120
    log-format-escape-json: "true"
    log-format-upstream: |
      {"time": "$time_iso8601", "remote_addr": "$proxy_protocol_addr", "x_forwarded_for": "$proxy_add_x_forwarded_for", "request_id": "$req_id", "remote_user": "$remote_user", "bytes_sent": $bytes_sent, "request_time": $request_time, "status": $status, "vhost": "$host", "request_proto": "$server_protocol", "path": "$uri", "request_query": "$args", "request_length": $request_length, "duration": $request_time, "method": "$request_method", "http_referrer": "$http_referer", "http_user_agent": "$http_user_agent"}
    proxy-body-size: 0
    proxy-buffer-size: 16k
    ssl-protocols: TLSv1.3 TLSv1.2
    use-forwarded-headers: "true"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespaceSelector:
        any: true
  extraArgs:
    default-ssl-certificate: network/mrmm-xyz-production-tls
  resources:
    requests:
      cpu: 100m
    limits:
      memory: 500Mi
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1wly55uepmquugkkd3jfev7tjhf46da63rrn4jw7d8l70kur5334s723lmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMzZwRTl5azgrbng4Rmhs
        WUhMeTdoVkFsUEZOTFZ3TUhvMEoySXpLeXdrCmpabDBkbWtVZ3BmblB5NzBTWkhi
        V2Eyc2J4ZkxINW4rNitCcVVrSjBGRVEKLS0tIGQ2YVdFbmxBYzBZVi9DYU1KeVNk
        YlZ4UzkxWFhtTEYvN2M2TVk5MnN3czgK/d3liV5+gdnHyuWFluqGznG1AuY4Rndz
        91TjLutdN5zYLwX+0bXsn2ilcEZqxY3KXctJvtJ4ZcjJ54K/AJfCag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-16T20:42:12Z"
  mac: ENC[AES256_GCM,data:QYfJD+Ym8pAyx0LAJpEIr2MVJ2mqTtEQ1sNNQmFQaMZ1oEpp+lK7nJwuzKVpcLmtHPE8tsYCqs/nU43WgbET2TFaJzNbAprlV6OPjVr6MkXxee8gjINhVQNYGd0xTQrqrSA/HhvwncmvlucDp5lJoUiXura2do3LSFgBMG5Gw6s=,iv:D0oVoiDv2n1gqJY34tHXMudp8gvyHeTv55WlcLAgdC8=,tag:FTxOammSafrc4GlpOPPZOg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
