# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:JifuMr4ef9dgNt76gq+h218PzTjqz7YCUZZpk5irtgHQpPk0UV+FtvZVMzYXo6lxh09EUofqv3mfzxsHtQ/vdz9kfnjOpu0ULm28X1TNwbvkFMAuxoEZJnPcSDhv6THtAA6ya66Ia5uxiu4BrIZzIPtybzu/V6ZyHyIOZj13rGMzGOY5msf5UTKoF35HmCZblxg9PmV0W5gaBDuLCCjjjkRuJahKfTPeC5F3XdBlJXXoioOEXg==,iv:LQo80nvWW0IzUK9JbvsPDSvEin1kPEqMdMW04gOuw5U=,tag:gkTIDg83kXL1WHyJqD4PsQ==,type:str]
sops:
  age:
    - recipient: age1wly55uepmquugkkd3jfev7tjhf46da63rrn4jw7d8l70kur5334s723lmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVjIydG44RVo5ME1Nc05Q
        RDVySkVqNGNLSXJTbGxZRHZMTFJOMnY5MGxzCnNwcDVrS1RCaEVlUzNBQXVURm9o
        dFl6MGNZS2pNcXk1TlJRSW8rOS9OZUkKLS0tIHIrQUNoeUR2L3hha1dhZkpxYVRk
        WDFMNXV1TU1ZekYrMjdtUkJXbjJLS2cKoHhk1ORWxCelPcijAN3xZ/5iOmZyFcYd
        ABeKO1ytG181wQ+Mjlv2D+VglRSqKelDB1Jja6tORtlwkn+SaMCNYw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-27T15:06:49Z"
  mac: ENC[AES256_GCM,data:fW6Z9H4FU5VpvjGO+LInsECkTM+kkNUN0ddBj7A5McZXlF4w19fbxMwxD0zlNJOKC1y2KfC6ol+t6lFC3+o93GXi2/oPESgbVS2IwYgfSZ7rhBKP+PykWL0mJbZ9UnFZ2Km9rPhn9aRBJJlIakAZXxpCJDW023rRdm4tIfCJsmI=,iv:a00vejIvIbe2WpU0RHPlqyznyj+bNpjbybTmZbNXYqA=,tag:LD78cu4SqqYgpk/ty5Ij/w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
