# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:+IrlFg75uTd2tSlbi62cQE6p2+RQhI+7qnUoM+M8RSoLDvZ4p39mfQNvHS4pLdgE6A6NxqwxXlAYgyjoCh7b4GXmCyPHayF7EWjkXOpDurfdZyQGIfyDTa6rTE1rykoTx1RV8WW3DiMM3U9ro2XM8/DqNkjSz8jzDiMZ01uCWw2MHUtU+LfzQ/aqLkuiniILSKtm9Ime9cHT88TPmGnB+5H7/nTSIWG6Gqm4e3NcnnND5PzgXg==,iv:93HVZVIaXDEm1yIB6WwcErWrcz4cgWzIqGqMD1ILtxM=,tag:HVWU77i6Vj92o78pGh45eA==,type:str]
sops:
  age:
    - recipient: age1wly55uepmquugkkd3jfev7tjhf46da63rrn4jw7d8l70kur5334s723lmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3YmZVSlBkbXNwd3VsMGVl
        SWdFNXBRNUxrVlV1dzVPUG9jWThBWFhub1ZRCllMcTVPenZqMVJQeUtuNHBNUC85
        ekJyOUxYYWZGQXVvWWtwcHE3cDVmY1UKLS0tIE9wOGN3aVoyVFBZUjRuU1JqaHhR
        WnZKbXhUVlVSaVdxNkk0NzZNaU5NbDgKHfeekFgI03NzEZ+MzpkjWDtfiTEsHzIA
        AoSzFWfEEUlantFQcm45xOhRjIC0Lyv0JuPzUEi911ELc2+QYnE1Tg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-27T15:04:18Z"
  mac: ENC[AES256_GCM,data:/2zhDPTYxS1AgUwjYTZWvznmlohstCdfJatDJtnFaNv4CtTlQNy/PtXg+caJVOP+L0aodjGWp2yhHECgvq5kiKok4K2VgtU4bSc+Mj60OGg48OjGgj5fnou3YP8RiuidoyzEHAFsIlQH0xAf1Jwi6vdG0KTcFUzL3ZW8vV1KsSk=,iv:BpOAay34HlG4qdO4PEGmyUS+j9F9B5WE4HWadU6xrKQ=,tag:I+PYv+zjxtej29IOe2bVpw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
