# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:2ydj9awA5rSZvM8d8buHL9p/aBJW3VKgnmhGahErv0La+pC+HzbZ9A==,iv:kRLgO12WAfmOAhjSRC09xt2s2bORIy5CmJduZxN9EyI=,tag:CuvJlJ9RO/7ma+yiqZ7PAw==,type:str]
sops:
  age:
    - recipient: age1wly55uepmquugkkd3jfev7tjhf46da63rrn4jw7d8l70kur5334s723lmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVVNRT0tJZlhvMGx4dmQ5
        MVAycTk5c01TYXN2VlBxRGdKamFnWVRCYUdNCmUzZWxwYTN1KzlPc3FDWXY5eEdU
        RC9zWm0xZzRkLzlBbTF2MENFSzRsUW8KLS0tIEhwRjN2RGlUT2xNNHN3cTdjZUlN
        dEdORVpTQ3hzd2RnWlJqejA0L09jU3MKOS4gvvkkQkOLvXgApzetZv9+36hNGKvT
        FT1W2NkRO175iMrodt2BoeScMDGmCnuTgBzuZoHDChxltYraIFwHGA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-27T15:06:49Z"
  mac: ENC[AES256_GCM,data:Y5rUaP85C5DTPWe2O7R9l6b0IIqi7RKWV9iUF+2XMC/T4lpD5z5FmY/ttwiuj7R6DU28cCSWHKzjQfM4BEmabOGP1djybtKPhAXbG/gBkmxdIJPsmhd+8ZXu40eqO8+tVddJpxm59hnNKtEQUW/GmfYrZBpCv6zc2InakYt7+yw=,iv:uqeQQAdcXU4IdQ7yWXYJ84hT1TwNAPq1UbB3Br1D3ew=,tag:jxlr5Y6WiZP869qrgoGRig==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
