controllers:
  echo:
    strategy: RollingUpdate
    containers:
      app:
        image:
          repository: ghcr.io/mendhak/http-https-echo
          tag: 34
        env:
          HTTP_PORT: 8080
          LOG_WITHOUT_NEWLINE: true
          LOG_IGNORE_PATH: /healthz
          PROMETHEUS_ENABLED: true
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: 8080
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: 8080
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 64Mi
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
    seccompProfile:
      type: RuntimeDefault
service:
  app:
    controller: echo
    ports:
      http:
        port: 8080
serviceMonitor:
  app:
    serviceName: echo
    endpoints:
      - port: http
        scheme: http
        path: /metrics
        interval: 1m
        scrapeTimeout: 10s
ingress:
  app:
    className: external
    annotations:
      external-dns.alpha.kubernetes.io/target: external.mrmm.xyz
    hosts:
      - host: '{{ .Release.Name }}.mrmm.xyz'
        paths:
          - path: /
            service:
              identifier: app
              port: http
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1wly55uepmquugkkd3jfev7tjhf46da63rrn4jw7d8l70kur5334s723lmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZmdmMWJiOWlxRGt1NzNn
        bnZQUWdzVWlOMjJYWGNwUlNobHpXRzlqRkZBCmFCMzZHWFhjeUlydGNiM2tBZmJt
        eWh3NFZLOGZ2MVZURjJ0ZUJUOVZ4eTAKLS0tIFhtMmsvUkxObDdtS283ckt1Smcr
        R0tuSTdYaDRvOFE0UUsraENGbzV3R0kKiNVDMhw1wK3xaEV3S32xeMSK5ISfYRwW
        bRwZxgfp1xVKj//M02mg4uavcwahRH9+cZjGHfnq/slk6VCPHrYrRw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-27T21:01:52Z"
  mac: ENC[AES256_GCM,data:4ukk21VCAY+rh8bRj+escn5gcs2oj9QAUhWmdTTT+/8Yg9HxV3MVQ7DRbXcFTrQZT7umazjDh/+xriUkn6gh785q0XP8PQ97OURKGcZ18a2HX8akbQRZBthyuDQyQIPQZ7+mEZym6I9vocJda0O7NsuoI4vGOmBD3zui7zh7dr8=,iv:XqCUda2jjhIrHc5ukkRl9/umxzNgEtK54saa/vgE4Js=,tag:/HPrHfXxeKfmRk2eBiDgyA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
