controllers:
  echo:
    strategy: RollingUpdate
    containers:
      app:
        image:
          repository: ghcr.io/mendhak/http-https-echo
          tag: 34
        env:
          HTTP_PORT: 8080
          LOG_WITHOUT_NEWLINE: true
          LOG_IGNORE_PATH: /healthz
          PROMETHEUS_ENABLED: true
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: 8080
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: 8080
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 64Mi
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
    seccompProfile:
      type: RuntimeDefault
service:
  app:
    controller: echo
    ports:
      http:
        port: 8080
serviceMonitor:
  app:
    serviceName: echo
    endpoints:
      - port: http
        scheme: http
        path: /metrics
        interval: 1m
        scrapeTimeout: 10s
ingress:
  app:
    className: external
    annotations:
      external-dns.alpha.kubernetes.io/target: external.mrmm.xyz
    hosts:
      - host: '{{ .Release.Name }}.mrmm.xyz'
        paths:
          - path: /
            service:
              identifier: app
              port: http
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1wly55uepmquugkkd3jfev7tjhf46da63rrn4jw7d8l70kur5334s723lmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXeit3TmlkNFExOXRqWk0y
        UmxkQVovTUVXbk9RMGp4RjZ3M004MmdQbFhjCi9xR1ZkL3BhOTh2cy9HRXFqd29p
        WWZ5c1k3RE5KeWkrNW1YQUJzQkZ5YncKLS0tIG5YU0FPZkNCQzNNSk80bDRNYmZz
        OXZ5bE1ieXMvVzVtZkQ0eTlrU21FQXMK8CWvGTAa50wdVar314dUyMJAwz+MlpxX
        stMQDv/OAlO4bMM6pYXkDg03/bptzHwhDx2emLfaXnLmFK9DfbkUgQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-27T20:52:07Z"
  mac: ENC[AES256_GCM,data:0uj50EVs3KNZQ/LynLvnX1Jzuo7ALQfmHjpghYnSqvs1YmfH66F5QGWmk6KNJtWaeUUWEjIsuTVGNHhUh7b3OGioRyEZERM7a3aoP71rjUUQPbcUjYn/Wb58uDI1sUE2EoO3BSAtP2sEui5dxnIbeHLSMYLhLjWiAkQvT5cAfT8=,iv:p7lFPM2XYHE826sdsgRMZj3MV+dQ4TxFDOjqi5k/Q0w=,tag:mE3RAaU+YxJX3EBF31CPfg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
