# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mrmm-xyz-production
spec:
  secretName: mrmm-xyz-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: mrmm.xyz
  dnsNames:
    - mrmm.xyz
    - '*.mrmm.xyz'
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1wly55uepmquugkkd3jfev7tjhf46da63rrn4jw7d8l70kur5334s723lmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJU3c3THRqaWxmTHhnNE95
        VlF6SFpFQlIwNkEwZFpJdW5QTDVISGZpekhFCjI3L1RNWnVLYVVCSEw2cmt6K3pI
        TXkwRlBjMjVNYVJzS29hRUdiemFvcTQKLS0tIGluOUwwZzRkbDlMYTJrYmRiNGlW
        dFR1THp2OWE1QXJ2OTdDRzlaQ3BWWUEKIlD+s2d18vmmbJJ1th+Et5i6sfkqP5jp
        SdIuDO1dUokJaqH5ysV2a6HBKKcecshBzbkQcbnRxi0RNlH3QV8vKQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-27T21:01:52Z"
  mac: ENC[AES256_GCM,data:hQyoEkRtAk8CFjNhX2cp/7tfQeh0/Lfx0rVYEvoleEXA5udOmQ8TAOQa5XFsruqwdA1tBrOZ3spz8h3kZ1WSMWPNHxxhlwyAQkRBTuee3eyTFXPDlNQs7Ra4yZr/kAPEZpCIx6UuXmOcogcL6RYMI1dZEuLnHEOnfWpsF0NzO/g=,iv:76aLUR6GALOOqmN+GqFSfr2+xgdrfupSiydMEESUIm0=,tag:zyfDVmhQMr+qUyg5sg1UhA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
