# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mrmm-xyz-production
spec:
  secretName: mrmm-xyz-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: mrmm.xyz
  dnsNames:
    - mrmm.xyz
    - '*.mrmm.xyz'
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1wly55uepmquugkkd3jfev7tjhf46da63rrn4jw7d8l70kur5334s723lmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WHJTV1M5NWZzZHJrOXhw
        c0JjV2lMbkJadjg4U0psU3d1YU5PZDhuQ0ZzClF1NmNkSCt2elpJRENLM3gveS9Z
        QVUvbDF5ckRYam5kU05hNjZaaW5sUjQKLS0tIGFvSFZkcGpaVHhuMEJ6aGRRQkVN
        Z2tqbU9iQlRkbGtmQVB4aGdFWGliS2MKyGPR18KZ5y4a+mD3PWlisTRDiMwkjQQZ
        ZgCwEOFHq1S+KcqP/6pqsWZEHRqrKzVjXd0/VAFJgZH9vgdc93ibTQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-16T20:42:12Z"
  mac: ENC[AES256_GCM,data:o17WanjkvIxygF9oXJCwUPtVj+ZXxxBP8coQlh0L0ejqNE33IqAPT1GGMMZS8xd6J7+pTrrlml92i+gvY4o5UbFx5VeSUNsTwm80IwxJ1eMdJjtzxhxn1a3gXQ0pBf3w1oQl/IuFEuSaJvz5TMUF5f4K1tBhiROhBSBuVA4kGmY=,iv:JuuX+poAX6t0hSs0SFQGoTbhZE6RYcH5z9YlyqkaR60=,tag:eUFVULWZGHTVxG57zlx/pw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
