# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mrmm-xyz-production
spec:
  secretName: mrmm-xyz-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: mrmm.xyz
  dnsNames:
    - mrmm.xyz
    - '*.mrmm.xyz'
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1wly55uepmquugkkd3jfev7tjhf46da63rrn4jw7d8l70kur5334s723lmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZFdmN2N4WE5CRmZUWFgx
        alMrMW9HMEs1N1JDSHpDM21hcHl2TEQ1U3hVCmJkb3lGejlMR1FCNTBRS3pCYkxT
        SkpNRFVPR1J6TlJYK1Mra0tmdDgyQzgKLS0tIERBVDNhRnhLREpXSDQvZ1JXanAz
        dlN6NWIvMG12a2hycDdOOHF6S0VBQ1UKwkXSwkiuXe9Lzz0D831lD2iwdpmIlvGh
        LWvmwcR/eZHIOrAWNxS7jMl6LbncaI1VLAVAhtEYVJLiKgmEzjslyA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-27T20:52:07Z"
  mac: ENC[AES256_GCM,data:fDYYZNZ0e8wX8o7h6p1Vuo1bbDKHKCY4CWy0XxLEH4Euwhe4lufP6P85XF/9Mh6Pq6TeY/pnoa0R4rOXuew0bY0PwMSYp5yZbINZgv5uJzmzYR3OCEcie09lzlRk0FOLivPw7hks6NBwgnmwNKUe3aum9pw6STvoO/mIZljH9p8=,iv:HvhzNo2PUTodUv8kUn+i/Df9Xwtz9xF1Lw/28PrfMcE=,tag:Y4OiLlS31HMJupYgFCV0xg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
