# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: ENC[AES256_GCM,data:GhcL,iv:O3ZNRrnB//yxh/IQ5/SGqH/RuuKCpS6SDIDni783IbM=,tag:3rtPJtLUW+knjbZsoEV7Jw==,type:str]
  url: ENC[AES256_GCM,data:GJWn1Z63AyiXsldrw2iYTw7CY12bb4D2kWNlILQJ2N6JULQ4qmzoJeA7,iv:evftMXDwUiIr10sfU4qanyq5T8zMOA1ku4/pNPjDu9M=,tag:nchUCfhA0U2xT/wgu/uqyw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1wly55uepmquugkkd3jfev7tjhf46da63rrn4jw7d8l70kur5334s723lmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdjhEcDNTWUc3bDBGT3Vx
        M29DQnRrVC9IL1JNVWJmd1kyQVNNTVJYUjFJCjYwWVl3UFVSNnJoYk1Demh1TGhZ
        eVcwcWQ1L2VMejFlNVVzaDlQd0MraVkKLS0tIFFoUS82ZTZWSmpzbmlCeUNWbDB5
        cm52ZzNUUnYzNE1IVjBuNThqY0FVVmMKO+h7IVJqSbLRVdpMUx7D7zJ/aMw9KNGI
        yYYysNuMKKws7+5m07wDj7ushUAGxun2IujQZp0UeCBHvLXsjtVztg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-27T21:01:52Z"
  mac: ENC[AES256_GCM,data:sEo1ezL+zuFlKcrAqn3TWE77Dr5NADXQ5ndiAjrshZ+cGQRbvwQB2hK1boA1bQ1lW4NBZL2Vja+6X0zt/GMVk2qil1ZWbmd88YgqP30xPKJiwDOJNtYqC9JYzQNEof5g5mErBpqUCMPTFmuzafuPMtL/1/CaLXkmhZa4V35YOI4=,iv:ed9hdekzs7y+v2e/p1jogkXeZnehWVvMeIbKEXR8MuM=,tag:6Zv5BOg+7yFMjH17gqaOjA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
