# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
        selector:
          dnsZones:
            - mrmm.xyz
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1wly55uepmquugkkd3jfev7tjhf46da63rrn4jw7d8l70kur5334s723lmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbVBFa3NrVWYxYmdyQ0ts
        OHpSMzJQVlpTSjhMR1RWdngyR2M4VDJocTNrCkdaeXRYa3BIZmRpN2ZkQTRyN1dZ
        YlJPVmJGNTVzVmNkTEJtbVk3all0bnMKLS0tIEdUb2tkampoSi9TRW1qVUl1VTla
        RldEV3E2MWRsVHlCVXZvOTVLZEp3YVkKUInCGDNez28fzrG/Y0F8LtVWSQ0r+RTt
        HgOJQQZorqv+oIlFWP+uGAZLaT5pSNRmva6H+MTqSYrQGZL2k6XJuA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-27T21:01:52Z"
  mac: ENC[AES256_GCM,data:yTZ1wxgjcNS07YvpIDhFeaGoEO5ney2ZlbTIH8CGhps4/3RgpmUZX0e59zvA9WsM5P0yA5zt0cyO0oL9l/fSPFWI1JZl7am+jvg17tfhPiIqNdMXV9vO/x6dsASFn2F7SDojRVvOZA8y0605OW87b5zdZoIUMIL1g55FyzS26C0=,iv:eW8F3pExnfgj/KNiRyM6yQVfDtbqjpDiAuA31gtr5EQ=,tag:cFs3tRvY9bncmiGCgEMpxw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
