# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
        selector:
          dnsZones:
            - mrmm.xyz
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1wly55uepmquugkkd3jfev7tjhf46da63rrn4jw7d8l70kur5334s723lmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbFFoQ1NzYnlwTWZuQnI1
        VnpQUTFucUEzdTZzWURiditzSnh5L1ozVkVzCmdqRkZ0cFZBbm54cUxGUmYwRWxL
        cEhUSzBWbnh4MVMrbllXeVZuOGVVdkEKLS0tIEtwcVZFOUFVRnRxbTJ2RitLejFt
        TGNvclFWbWJxZFhTWEVXKzIyMVZKbzAKJX6cnOctoHf+WW78OFk1ovNn4M2mT6OY
        XPMP8ADg9C4WpF46p53NJqJQyhW8Hl34mq4kk/w5U/OwR/f30f4BSQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-16T20:42:12Z"
  mac: ENC[AES256_GCM,data:xmuppngAQJeo+GS+xF66cKOA4DgzsVAx+3ZursEKf/fVXFoMvR4HRZOgTs79rWL2TGpmzq2MVmIN5Z731Z9b+KNHpHqzNVBTH6P0RDofkIPo7F99livStDQrCYnlk2SspTkk6GO588HNIdoX4X9pfZ4K2EpwEujd/XcxsBjdO6E=,iv:8H6b6xFHw+CeYX73NW2Btl37SMpc7wULwFTK5FuhC4U=,tag:KuKME634svzw7zVIt35Xjw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
