# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:dxCI80+BUujZGzORjsNHdTo7b4XzdQnFmggWAxYql1yxgc5eHA+d3g==,iv:VZaz0Cf+/JwyXP9PkUwLCs/8HDp1PtK505r49YmlslU=,tag:RY41wo6RYy37bYAlWl415A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1wly55uepmquugkkd3jfev7tjhf46da63rrn4jw7d8l70kur5334s723lmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcTE1ZFVPNHJzMnZyOHBL
        VllRdTJKdFFXTk94OWl6WVdmTzlGTGF0d1dZCnVaQVNTMjEvN3ZjaXIwMTlSN294
        KzZWUHhDUzNvT0hXV1ArR0JkbG1tSUkKLS0tIDYwVUwzNEJxM3U4TTl4RVR0eUNq
        bDhaM3Vmbks5Wkd5UnBBZ3k2RXIvOTAK2+GEmGZTs+O3IxSRimUgIzrD4eDoqPLm
        +6wLzQunhbWJ6zMQzNsxTO9f5CRRl6CXT2nOYkbHwEiAXxT6hQQzDg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-27T21:01:52Z"
  mac: ENC[AES256_GCM,data:d3XNiIHjvrxdzgYxwkty+qahkeHAE7pI/hL0OsSVsl26T0mY+c8NqwcJrbiQ9ZD6qegn56hYVf0yy3zEaPfPjomxQGdoOMU/cI70HtsHbzitFvj6w9SNppXRb2hfoJgRBkmZM+VLkA3VEhTLnwSFTQE8h0kicINiJgsZ1mNQUN4=,iv:lQUVIb+qe3arjJwTTZgFyBcqcHgoI91uWdv6LkM7aWo=,tag:2Cv5J/Tasav6SZpUqBYnbQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
