# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:bA06C6rnrjbsfQVXxizskdA4f+YaKcv0NRGFYbAcdMmTGhohFYM4fg==,iv:EuonAp7Z5CSVILrRna2EOsJmEmfhJx/NAwmhyYRBy9U=,tag:nyXnR/1+AzbxoOgEJ820Xw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1wly55uepmquugkkd3jfev7tjhf46da63rrn4jw7d8l70kur5334s723lmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnaFNiUHN0UzVjSmlUSHhy
        SmZDaGpHdWRud3pxRzhycVRxQVBTc1dxVFdVCnJIblZGT0JaVEJTTzM5M1g0RkJH
        ZEltTTEvUkpqeWlLRjdMeWExaWdFNjAKLS0tIDBzdEVVT2NRY3F2TlhYSkxIZHAv
        N3hUL0VkZGxaTy9OQlJ5d2NZbEpOYncKqycfC3OZVEBrD31VgDtuJDiV+w7n/IXl
        2sbEOvfYoXKG+ALQZoK/kz9CxsG/z6rQFRT6l46DCPTZkzxEv30G2w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-27T20:52:07Z"
  mac: ENC[AES256_GCM,data:nU27+LpcczHvGfRega3+KeJKn5Z/vi5Y1TXrREL8AUo0ujHwdsIoUrlfwsa1WvEkY+Fh7hzugFn5tWBwND58cegE+KJNuzArxN6rKUep2z0Q6ui6M3zGxd0aTG5iEIiNoOGmdDPRL3jF6gKbhW9dvjwbIk31HwMssAt3lTtDHDI=,iv:vYyRBLvxuxHgN9mUwDS/LZuVi8jFCuMI2MSLCZnVeNM=,tag:+9iwwgyIZePtSxkSx+DcXw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
