# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:DCNDj0MI0UDu8wIizVOjT9E9EctPlIdEby4I+uyQGsjyxDA0h3tlqA==,iv:SDXdahNtftB4q0W2a2EyC4IX7SQfOsSC89r8garAndA=,tag:Aud081BNwJAhJyPvpPNUlQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1wly55uepmquugkkd3jfev7tjhf46da63rrn4jw7d8l70kur5334s723lmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3QWVMdEQ3VE9WcGNWRFVi
        Qm8yZStycGlOQzdCa0N6Z2N2Nm4yRDNxTjNRCnFvSFdvK1YzWmp1WEEvbC8wK01W
        aFlLcDlxTkdwZmFUbVpNUHI1dGI5VkkKLS0tIFIzdktyM0hvRXVkMlEyQkFZVXpT
        QWltTFFmSS9TQ2ZnTjdjaWdmdVM1WGMKxm9qj2R8dEHP7vczgd9b8emqN7XV5Fld
        Zms93MYeO2NcHwgLi1dLa5gYolY506M0gES3N2aDG8l/5OWNJ2TPyQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-16T20:42:12Z"
  mac: ENC[AES256_GCM,data:dw1qFrhvkWIHPZl6A0+rLA20XJWGOONS51jRfcmp9Op71gNcdo0TpXviiI192tWW4j0+VcJ8IcOHONssy6kUg6q8Qsc7Sedl96pFDlPKVHkIjQpExx1a1ET7pogage7n+vRJt6a1FMu2v4V54Yb+pvulAQGXXzQwtSwbHbmUgMs=,iv:IhcuuvpPLwWW9inEfZ4TYaULwlvvZyyeu/lGqx+xpWg=,tag:dQkGNPUlJdJ2JTFEOV1kOg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
