apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:8vhpKFboSieNR0o53U+pUL8Fy73rciLQBPwYGZhslIIJvj+BT25ozw==,iv:QRAWqrXF5kX1VZ5W0tQyTMCqAQFnmW9qKSzIvNg7u9k=,tag:U0cBVe+ePHgsA+9pTuQ2Og==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1wly55uepmquugkkd3jfev7tjhf46da63rrn4jw7d8l70kur5334s723lmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5d2VHVys4TUhJQjNGbWlY
        aHRXUmJEK2JPcGlOMnphQzQ4bzByTkpDLzEwCi9GbUJFK1VqV294bWhDdUNOL3g3
        QndJYWJzSmR1SEl6WjBGbks2eFJMdFkKLS0tIFNQbUFheUp6WW05T3ROZFVxVlJm
        NFVDbVU3a2gzQWNiK1ZsWjVDc0JsdWsKl5+VzeYL2YJ8uFyMuC9pcnxNZz0HzdnM
        YgVxBBPRwIb5bVayFl2hYAlCbzWkZ1/niV+0sTlZ5iIpf07gprSc1A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-16T20:42:12Z"
  mac: ENC[AES256_GCM,data:GEMZBHgwvSmxdmGF9WCVH0i078j6rhHrj0lMywVG0ArPBgNvDbhzCaNjZIqUyWKbZoc7x1Vzy+C297Ew7FoI/cQpunArRZi8o1NxkSwQzk1/r8Bh69zmwT9VO/NH3H7xjHQpvCaYA02/v+pnx0ihNkKOXGOPMHvqIV9Tld2daeM=,iv:lhHAbDPTv7J2atYZBvD7LywJk3ReMTBRnUCyurQgbIM=,tag:vJ+SZr0ji4mvFRQ44dd2tQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
