apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:x4/cqDLb1MQbnReh7z+dH0gLQa0HqYYIMp06sZJUrW8AvMqzqrtq2A==,iv:y8s5NVvsHHZXRLeZQkkGcp3B18cos9C/hxdxVBWGwyA=,tag:RIFc9nCsxc2GB/tUU+yPJQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1wly55uepmquugkkd3jfev7tjhf46da63rrn4jw7d8l70kur5334s723lmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncnJNdzdxUUhGbG05UmhC
        aG5RL04xV2tHOHBKejR4TGswSGNKaEw4ajJZCnhZWitPZGdFaWd2RnBGVDZZVUFM
        SWh6UElQd0JjeWxlUFFyZ01lcVg1c3cKLS0tIEI5TDUxSEFJOXpNV2lGYTdDaXhm
        ZzFNNWg3NXhrTkp2aWd4aFkwUmI3SzAKqzHIzeO8olm2pl2nFSLfgyqaIyd1tE0A
        GTRCklpAJQsTt7WcZCP0QSS2n1r2triaWeR3nbEOhq01QRLgM+8OlQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-27T21:01:52Z"
  mac: ENC[AES256_GCM,data:Kei/pfb8fFVvydVLqZ9FgP1UI+S4j9PBSeA0n+f7XfPpGfJhJxhfkoEzPgB3hN5DkO9wmVsuRAIJMLBvVKY89iQTEU+2s/CP4HsdEHSNdhfrOuyriKtRs85/1GTuI0hWzpVfVVaKk6cxZSVWNcbVzDrgpDb4owETpbaskNqv0M4=,iv:RrCjrNN4UAs8KBbLZTwxWCPRrZk1YRhREOBKU+5E3eo=,tag:rwlqhL1b8We4QCoS/b5jBA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
