serviceAccount:
  name: tailscale
controllers:
  tailscale:
    containers:
      app:
        image:
          repository: ghcr.io/tailscale/tailscale
          tag: latest
        env:
          TS_HOSTNAME: home-ops-router
          TS_USERSPACE: false
          TS_KUBE_SECRET: tailscale
          TS_ROUTES: 192.168.69.0/24
          TS_AUTHKEY:
            valueFrom:
              secretKeyRef:
                name: tailscale-secret
                key: TS_AUTHKEY
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
