# https://github.com/tailscale/tailscale/blob/main/docs/k8s/rolebinding.yaml
# Copyright (c) Tailscale Inc & AUTHORS
# SPDX-License-Identifier: BSD-3-Clause
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale
  namespace: network
subjects:
  - kind: ServiceAccount
    name: tailscale
roleRef:
  kind: Role
  name: tailscale
  apiGroup: rbac.authorization.k8s.io
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1wly55uepmquugkkd3jfev7tjhf46da63rrn4jw7d8l70kur5334s723lmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZlF5VTRKS3FHVDNHYVdl
        SVhMeGcrTkVFMlNFL095THFBKzAvU2pZRlJFCm1nVzU3bjNvdlY0RGJ2cVVoTzVU
        QURtQ0NJRDd2Mk5FblFuZWF1NXpIU00KLS0tIDFjeXllRGN4OCthY2pxd2k0K3FZ
        VXZ5WVpKR1o1QzZFVnkwdWFWaXUzZncKUL4LA5DNyaiyipTBIYpUjyT8mFIsxiRz
        gp+T01dltfFCe50AT0IABl7sHiCwa9IXdKsAv0RBwlB+vw+0TCmLug==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-16T21:15:51Z"
  mac: ENC[AES256_GCM,data:mdWCV7KK0+CAXVsKRoPHkThBbX/d9YXHEOnhQPh0oxkpL34dwgMTkWjJITb4xCrBJ5HSafXoFCdmunA7DM/zTbamnOR6nzsrk0Qb4px74Q+HuAcRriyScNRY+VoFL9uC2a+0USKz39Kphd38/5graey4RvClnI8Sh3kVBqB1GDs=,iv:BiCAKIqRXCTIEAAkjIuHYj6M4WDCrZ0ylSjwwSyvym8=,tag:ITN6H1qgdfyzAk0F493ObA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
