apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: tailscale-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./secret.sops.yaml
  - ./role-binding.sops.yaml
  - ./role.sops.yaml
  - ./serviceaccount.sops.yaml
