apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TS_AUTHKEY: ENC[AES256_GCM,data:lftiaCKtI3ikKD1CSzbU0YyV3mpAvWzDZZ/k6Qjs3W7tz+5bGaS67qhSiLwQ3qhaQRW1kUsc4/aaC8RONw==,iv:HOhxykNY6klSC/+m7AAN5k/qjMiMp7xmCPk+WZG2+C8=,tag:LbeH3qaUW4jZYxMuYBvghw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1wly55uepmquugkkd3jfev7tjhf46da63rrn4jw7d8l70kur5334s723lmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dGs0c1lZQlY5UkZ3UHlO
        eFZZM0xYbVJjbTRkdGRINVdRREFpS0N5bEQ4CnJMSE5LdEpmRTJtM2grRDVKdWRi
        emtKZWcyZkY5eEJweUxtQzdURUZYNlEKLS0tIEVTRGdRWGZHa2xRdzZBOERxcjUv
        M1o0QnVmMGJKSkxIdlFLVE16RGpVUUEKfdhJ1FY/Gm9qY9r7KsxkBfofha4N0/M0
        l3cwuuhotvo25T6kVK9sRzFJLOx6mJccZjECbOH8PKWBZ52Ao6PzzQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-28T20:16:19Z"
  mac: ENC[AES256_GCM,data:mhXPzsR/HIKwCi/un+pe7HolwXRtXzwJjMJ9nSldXuESUaWjgNDrbb6JAocV/W4hIG8LlVP+X5oosLd3n17nZczwp/lqaeSEofQT3jVLAJP5+NSPJGp+3f/8VZFuSbSA/KVLle2uCWYUKpkFn7hHcry9NN67ELadUoxhWkcXWmg=,iv:SoUxooYuP5odZWRzjpI+bDPcizqCjpNwc8iFnSik998=,tag:qTCHkcdIfM2mYL/Ru5Exsw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
