# https://github.com/tailscale/tailscale/blob/main/docs/k8s/sa.yaml
# Copyright (c) Tailscale Inc & AUTHORS
# SPDX-License-Identifier: BSD-3-Clause
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale
  namespace: network
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1wly55uepmquugkkd3jfev7tjhf46da63rrn4jw7d8l70kur5334s723lmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtN1ZCSWY0a3JzS3V1Q0JM
        RkFUeVZyUU1qSmVyQlNoa3NHK1ErcGxKV0NjCk9jQUg2Q25BTW41TWFoV204VXhW
        Rk96aXdZMU8xS09lSnM3MFoxQ2dBN3MKLS0tIGlmSDJwNjRLVDZWZ0VvdHFWTHpQ
        VmxrYk9KZkdOS1Y1V0c0TUhXa0hSRDAKg9p4wDrD0FxUli8FLzDvYZJzCAoNF+5X
        Nmj1OppGRoMveL1OGTCTold2aeZZAlwtP6aB3ST04VL4ZiTtMuhQLw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-28T20:57:19Z"
  mac: ENC[AES256_GCM,data:ltgvK++BdruRdI9TMPGE2ij2Z0hMiHx3tsnVh5UqYaPsXcVj5VilHT8hDWdvxPY0nOQL2siZm7tsYK8tfCXcUYnyf/26jXFn2UMCiP+cyoM9gKXbVsRiuZ+LabicgICYaRToFTJwtiH2uirWW+o/PAa9o58Hr0xdxnlu1MKPKhg=,iv:xXQCB4pzkJZSNjRvLAtkDAclMEwe4Nlkkpd395oKQLI=,tag:sDSVfvEabv7beVgF5D/Z/w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
