# https://github.com/tailscale/tailscale/blob/main/docs/k8s/sa.yaml
# Copyright (c) Tailscale Inc & AUTHORS
# SPDX-License-Identifier: BSD-3-Clause
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale
  namespace: network
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1wly55uepmquugkkd3jfev7tjhf46da63rrn4jw7d8l70kur5334s723lmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtN1ZCSWY0a3JzS3V1Q0JM
        RkFUeVZyUU1qSmVyQlNoa3NHK1ErcGxKV0NjCk9jQUg2Q25BTW41TWFoV204VXhW
        Rk96aXdZMU8xS09lSnM3MFoxQ2dBN3MKLS0tIGlmSDJwNjRLVDZWZ0VvdHFWTHpQ
        VmxrYk9KZkdOS1Y1V0c0TUhXa0hSRDAKg9p4wDrD0FxUli8FLzDvYZJzCAoNF+5X
        Nmj1OppGRoMveL1OGTCTold2aeZZAlwtP6aB3ST04VL4ZiTtMuhQLw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-16T21:17:01Z"
  mac: ENC[AES256_GCM,data:YgJgs38GItmvoi/7DagP7OBxPiUBFBqRSyVG1orPRCaNp1MfJb53vKaLutX+1rozW5Mb1SwPd7jNwAZ10xpTTd73eLdpOylwE3jhqIGrB7kH/Qp8b1rD0SVOYmltJ7bdlDBwH31ImXEaTlTnDX2hQxDWQJVTy4ysIHlz6BA45OY=,iv:j6i4s1rJnK7N9ctuNNcMvmQsm8rpI2/+slVGoJ+ZLMY=,tag:QXNp4TdGYpsZB4SthXhnMw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
