apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-configmap
data:
  config.yaml: ENC[AES256_GCM,data:06BgsVIAaxW3ZrChzEDzZz0EbkbX+fad3Ntnnk3co+0ma68C/Tr612SNQrIryxz8NwcmqFoMxKPMVT6fi3VQd8h17WeP2Nbipl78nKPdZeT7REj4Ya2xqiafCLEynfPIphDMvjtVNFBm+B/7q9i5SZq5NVT4rANdBWCaGNQWZiqkj61gW4cH8RWyl/chfVUMazfXTbNXFXHgqIKzPdbzo568cN0EkobaAIQ6LfyE5SjtttUhGRkZKg/fMrA+AQ8mlkdmU0QcczVtDB9xBLTG/YrAajMaeIQV1uKGqNqLL/FnPMRk7sqCC6hVeGmke/Lw/IOXqmVQQ4CiyAvQfAqiw58u,iv:XNHymDz1bDUznHt0/zSQMK2SHA02Ny8mcpyC4X6v0Ek=,tag:Nqsw5oI1nRdClxFqGiZKXg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1wly55uepmquugkkd3jfev7tjhf46da63rrn4jw7d8l70kur5334s723lmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2eTQvY1B1RVJyZGZkQUxw
        WjZ3cGttNEFTT3J0VlBydXNDcGpPWEZkMlNNClkzMHNuU0txMEpFODQzY2NaaVAv
        NHgrb1owU1pPUWZTZ0pqSERQTS9PWFEKLS0tIG51MFhuRS9ZSktCOU5hYi91Y2h4
        MjMvbStBQjVCRVZWTURBMHlYbU4wdHMKMCFia3lJEd8gY1gM47PS5Y6b/wA69ukO
        adTiYvQhNec+Vkptqkzv4e+kvahomutUW+keEgY/T2V7rP6/zffjRA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-16T20:42:12Z"
  mac: ENC[AES256_GCM,data:7/AgD8THPVoJB1MaXQJ6TKM6va/am3v+mhfl8BGTuIDmRV2aR0mDp542vG2k4PNC6/zXNcBGd89jfqemr7I6mxr+08EIafmJgB/oV8fj+Ey9mN8jezH6ctomGRHx/46iNoy+7uJbFFnZOHWZl/iZ+5l+BToR/e+WeJczc9sUdXM=,iv:1uFbekUw3quobCN1Hja1VzB3II+mV+Ilpxo5JnOABP0=,tag:m7jKEzMahcb4U9bh4JYHdA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
