fullnameOverride: k8s-gateway
domain: mrmm.xyz
ttl: 1
service:
  type: LoadBalancer
  port: 53
  annotations:
    io.cilium/lb-ipam-ips: 192.168.1.51
  externalTrafficPolicy: Cluster
watchedResources:
  - Ingress
  - Service
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1wly55uepmquugkkd3jfev7tjhf46da63rrn4jw7d8l70kur5334s723lmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSDN0V09KZzFtSUdlVnE2
        NzgyMnFUaUZPeWkySTd4UUlFNG5QZW05UDBzCnpwVVZZMUR4eWJyYTArdkp0Z1d3
        dDVmV3Q5MHJiY0xVeXBqcStZYmJZdTAKLS0tIGdxYUU3bnR6ZjQ2OXpSb2diQytQ
        V3R1OTZPdDB4a01vVDAzSysvV2IzTVUKUc7yw7841+tgdxzhJLTvFYE5LbSA2HK+
        gCiG63rh1XgNIERwXkHx3i9cFBvOq+4vxdlGjQso6gqxtW2Klq3EZQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-16T20:42:12Z"
  mac: ENC[AES256_GCM,data:4VMEb9E+xd0Y9YffxU5KPC2hc/AIUTIIaP+uKKBz4lzgjxAE03tZ+HowaTbBvtjq8gpoanfFz69roApKRwszt8kkX5INlPapBPZZa7h4qsXoYAa5rTGQ35TNzKQTgYLP3pyqJqJ7IU2VmkKLh+N6BSkkMEyb1EI4Ax4DullarNg=,iv:ZlO72hBMRLCfGfLyzPVexzuTAxdM0E000W7AmcM8xgg=,tag:jH7xtKVWMC/3xTFUs/9FMg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
