fullnameOverride: k8s-gateway
domain: mrmm.xyz
ttl: 1
service:
  type: LoadBalancer
  port: 53
  annotations:
    io.cilium/lb-ipam-ips: 192.168.69.51
  externalTrafficPolicy: Cluster
watchedResources:
  - Ingress
  - Service
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1wly55uepmquugkkd3jfev7tjhf46da63rrn4jw7d8l70kur5334s723lmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUTThqUGMwRmIwOXhsUXRn
        ZDBFazVNSXp0V2YwYytpRjhDOWtIQllRMUVJClg4eEtKNkkyamFLWEpuc0dEVHpO
        eHplcDRLeUtQVWVRdEJiSmV4Snd6TzQKLS0tIG0rRmVQbVVTMEdubi9GaGo0WXVm
        a1FIU2JuSkdLOER4Uk8rUm9HSDR2RGMKx8Pxi8A3rxfSlfGtakk4orJvbBZacZiL
        nHhPxwASSvxxE15nuvCn09v8+DoakxVKVUbm57DnCzapSFPeEbP3UQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-27T21:01:52Z"
  mac: ENC[AES256_GCM,data:Z/UmM9eCPTqQu9z4+zQMkGoBjFJMnL1X+3T+0woGkTHCFZiPO2ZzhbsNTdQZH3XztM9qMtG5sYkE076TpchGxc3LgX5SJEtXuUklHv8gS0x1+/b91eU62xgfYJK8V/5shIOn3uXd9UwJy6X1AGBbzyqBEAnaci2SG3R5BdTw7FU=,iv:wzjNGUyWRJWaPcNQRSUAmUJ7fSy2j1BSIpZpsyGaEtU=,tag:D6AD1afRfEb48Hv00J9g4Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
