apiVersion: v1
kind: Secret
metadata:
  name: test-mofos
stringData:
  halo: ENC[AES256_GCM,data:dUdb,iv:JufuyTefuds2tJ9Jd8mGxaDMJzmFA+tMxQ7uEl/keT0=,tag:upckxIYwvVGS0WtIfBBwhQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1wly55uepmquugkkd3jfev7tjhf46da63rrn4jw7d8l70kur5334s723lmp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOaW41WnBTdTlJdnRZZGN3
        UEhxTmRvNXJBYks2OFhKUzhWRVJnaS9kZ0FJCnhmU09BQXFKbnhENGZFYVNxRk44
        dmdkRGt5ZmtUbVVFeVJaRU5scS9DTVkKLS0tIHFqVjFqSW9tK1RVVU5LNGhnTk9l
        bGJDb2FwTjRpdmZCOGxwZ3JzQk9qV0EKs9gC0RJtyu0ttFAJZHp77AuWZhQiQyrn
        yuzAvQiENTKmdx55mIYcfq5K782gbeW6agycS/7apfVuruADNjf0bA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-17T14:21:54Z"
  mac: ENC[AES256_GCM,data:jADCPbSA9B6hsacC0OI3qZT7Lz31G0we/R6Wbuqyk4L5jZUV4oH/1n6oVwsYZu1fgLboj7l0h3vvmk8bJ5di9AcovkX6TVUMCM0+2RhinRB5mIhg2F2lBC3LdUn6h5lEPpxJWAdnYcn6Dr7R2lc/MU9mI/Gfxl01Q7irXD6HY1k=,iv:m/3IbItGx8DdoRDcSOy1FrcjvMdfvxGY6l2Twgp9Vg0=,tag:CoC9GAbkiZpw4AN2uxPNtQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
